### ISSUE TITLE
When to process photos

### ISSUE THREAD

**Issue by ShaneBerhoff** [emory-worldline/worldline#32]
currently photos start getting processed on app entry, but can also be processed in stats page.
thinking of moving the process button to settings, but need to not be able to process twice at once.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

We're moving the process button from the stats page to the settings page, and adding logic to prevent processing twice at once. We're also removing the processing logic from the stats page and adding it to the settings page.

You can review changes in this commit: https://github.com/mnmnk43434/emory-worldline-worldline-32/commit/3c248b95ce882fb32697a406fef3c4628adf5c67.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
